[package]
name = "dictexprs"
version = "0.1.1"
edition = "2021"

[lib]
name = "dictexprs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
[profile.release]
codegen-units = 1
lto = "fat"
