[package]
edition = "2021"
name    = "dictexprs"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]
name       = "dictexprs"

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module"] }
[profile.release]
codegen-units = 1
lto           = "fat"
